pub mod store;
pub mod embeddings;
pub mod memory;
pub mod attention;
pub mod router;
pub mod acp;
pub mod backend;
pub mod errors;
pub mod learn;
pub mod orchestrator;
pub mod observability;
pub mod rs_search_bridge;
pub mod graph;
pub mod simd;
pub mod cache;
pub mod spine;
pub mod db_path;
pub mod llm_gate;
pub use db_path::resolve_db_path;

pub use acp::AcpClient;
pub use backend::{AgentBackend, ClaudeCliClient};
pub use attention::Attention;
pub use embeddings::Embedder;
pub use errors::{LlmError, Result};
pub use memory::Memory;
pub use orchestrator::{Orchestrator, QueryResult};
pub use router::{Route, Router};
pub use store::Store;
